version: '3'

vars:
  SETTINGS_DIR: '.'
  TASKFILES_DIR: 'taskfiles'

env:
  SETTINGS_DIR: '.'

  CONFIG_DIR: '{{.SETTINGS_DIR}}/config'
  SCRIPTS_DIR: '{{.SETTINGS_DIR}}/scripts'

includes:
  go: '{{.TASKFILES_DIR}}/Taskfile.go.yml'
  python: '{{.TASKFILES_DIR}}/Taskfile.python.yml'
  lint: '{{.TASKFILES_DIR}}/Taskfile.lint.yml'
  format: '{{.TASKFILES_DIR}}/Taskfile.format.yml'
  git: '{{.TASKFILES_DIR}}/Taskfile.git.yml'
  aux: '{{.TASKFILES_DIR}}/Taskfile.aux.yml'

silent: false

output: prefixed

tasks:
  clean:
    - task: go:clean
    - rm -rf .task

  format:
    - task: format:all
    - task: go:format

  lint:
    deps:
      - lint:all
      - go:lint

  build:
    - task: go:build
    - task: go:release

  test:
    - task: go:quality

  # ---------
  all:
    desc: run all available tasks
    cmds:
      - task: git:info
      - task: clean
      - task: format
      - task: lint
      - task: build
      - task: test

  # default 'format & lint' target
  # ---------
  default:
    desc: clean, format & lint
    cmds:
      - task: git:info
      - task: format
      - task: lint

  # Copy over the project specific files
  copy:
    cmds:
      - |
        # cp -r .vscode ..
        # cp Taskfile.yml ..
    status:
      # if the files are already present, don't copy them
      - test -d ../.vscode
      - test -f Taskfile.yml
