version: '3'

# TODO: Change to vars and pass to each taskfile (?)
env:
  CONFIG_DIR: '{{.CONFIG_DIR | default "./config"}}'
  SCRIPTS_DIR: '{{.SCRIPTS_DIR | default "./scripts"}}'

includes:
  go: 'taskfiles/Taskfile.go.yml'
  python: 'taskfiles/Taskfile.python.yml'
  lint: 'taskfiles/Taskfile.lint.yml'
  format: 'taskfiles/Taskfile.format.yml'
  git: 'taskfiles/Taskfile.git.yml'
  aux: 'taskfiles/Taskfile.aux.yml'

silent: true

output: prefixed

tasks:
  clean:
    - task: go:clean
    - rm -rf .task

  format:
    - task: format:all
    - task: go:format

  lint:
    deps:
      - lint:all
      - go:lint

  build:
    - task: go:build
    - task: go:release

  test:
    - task: go:quality

  # ---------
  all:
    desc: run all available tasks
    cmds:
      - task: git:info
      - task: clean
      - task: format
      - task: lint
      - task: build
      - task: test

  # default 'format & lint' target
  # ---------
  default:
    desc: clean, format & lint
    cmds:
      - task: git:info
      - task: format
      - task: lint

  verify:
    cmds:
      - docker compose run go task
