version: '3'

includes:
  aux: 'taskfiles/Taskfile.aux.yml'
  git: 'taskfiles/Taskfile.git.yml'
  lint: 'taskfiles/Taskfile.lint.yml'
  format: 'taskfiles/Taskfile.format.yml'
  python: 'taskfiles/Taskfile.python.yml'
  go: 'taskfiles/Taskfile.go.yml'

silent: true

output: prefixed

tasks:
  info:
    cmds:
      - |
        echo "Root directory: '{{.ROOT_DIR}}'"
        echo "User working directory: '{{.USER_WORKING_DIR}}'"
        echo "Config directory: {{.PARENT_CONFIG_DIR}}"
        echo "Scripts directory: {{.PARENT_SCRIPTS_DIR}}"

  clean:
    - task: go:clean
    - rm -rf .task

  format:
    - task: format:all
    - task: go:format

  lint:
    deps:
      - lint:all
      - go:lint

  build:
    - task: go:build
    - task: go:release

  test:
    - task: go:quality

  # ---------
  all:
    desc: run all available tasks
    cmds:
      - task: git:info
      - task: clean
      - task: format
      - task: lint
      - task: build
      - task: test

  # default 'format & lint' target
  # ---------
  default:
    desc: clean, format & lint
    cmds:
      - task: git:info
      - task: format
      - task: lint
