version: '3'

vars:
  SETTINGS_DIR: '.'

env:
  SETTINGS_DIR: '.'

  CONFIG_DIR: '{{.SETTINGS_DIR}}/config'
  SCRIPTS_DIR: '{{.SETTINGS_DIR}}/scripts'

includes:
  go: '{{.SETTINGS_DIR}}/taskfiles/Taskfile.go.yml'
  python: '{{.SETTINGS_DIR}}/taskfiles/Taskfile.python.yml'
  lint: '{{.SETTINGS_DIR}}/taskfiles/Taskfile.lint.yml'
  format: '{{.SETTINGS_DIR}}/taskfiles/Taskfile.format.yml'
  git: '{{.SETTINGS_DIR}}/taskfiles/Taskfile.git.yml'
  aux: '{{.SETTINGS_DIR}}/taskfiles/Taskfile.aux.yml'

silent: false

output: prefixed

tasks:
  clean:
    - task: go:clean
    - rm -rf .task

  format:
    - task: format:all
    - task: go:format

  lint:
    deps:
      - lint:all
      - go:lint

  build:
    - task: go:build
    - task: go:release

  test:
    - task: go:quality

  # ---------
  all:
    desc: run all available tasks
    cmds:
      - task: git:info
      - task: clean
      - task: format
      - task: lint
      - task: build
      - task: test

  # default 'format & lint' target
  # ---------
  default:
    desc: clean, format & lint
    cmds:
      - task: git:info
      - task: format
      - task: lint

  verify:
    cmds:
      - docker compose run go task
