language: en-gb

# Paths are relative to this file
ignorePaths:
  - '.build'
  - '.exp'
  - '.cache'
  - '.task'
  - '.vscode-server'

dictionaries:
  - bash
  - cpp
  - golang
  - python
  - default-words
  - project-words

dictionaryDefinitions:
  - name: default-words
    path: default-words
  - name: project-words
    path: config/project-words
